### ISSUE TITLE
PHP 7.4 - Deprecated Functionality: implode(): Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by paugnu** [DominicWatts/Faker#10]
Hi,

I'm getting the following error when trying to create fake products:
`Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/vendor/dominicwatts/faker/Helper/Product.php on line 169`

I'm using: 
- Magento 2.4.1
- PHP 7.4

In the [PHP docs](https://www.php.net/manual/en/function.implode.php) we see that passing  implode ( array $array , string $separator ) : string to implode is deprecated. It should be  implode ( string $separator , array $array ) : string

**Comment by DominicWatts** [comment]
Thanks
