### ISSUE TITLE
Possibility without "question"

### ISSUE THREAD

**Issue by gitfvb** [DominicWatts/Faker#8]
Hi Dominic,

Now I have commented out the question part as I want cron to automatically create customers and orders for a demo system. Maybe that is also an extension for you to allow the creation of the data without asking the user in front of the bash.

Cheers

**Comment by DominicWatts** [comment]
A good idea

Although you would need to rejig all the console commands. I think you could implement something like this

    $helper = $this->getHelper('question');
    $question = new ConfirmationQuestion('Question?[y/N]', false);
    if ($helper->ask($input, $output, $question) || !$input->isInteractive()) {
        // stuff
    }
    return \Magento\Framework\Console\Cli::RETURN_SUCCESS;

Feel free to experiment with one command in particular and submit a pull request and I can take a look

**Comment by DominicWatts** [comment]
Sorry meant to say should then be the case of using

--no-interaction | -n

https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands.html

```
LONG VERSION | SHORT VERSION  | MEANING
--no-interaction    | -n      | No interactive questions.
```

**Comment by gitfvb** [comment]
Ok, need to try that... until now I used the dirty way in commenting that part out ;-) :

```
if ($generate) {
            /*$helper = $this->getHelper('question');
            $question = new ConfirmationQuestion(
                (string) __('You are about to generate fake customer data. Are you sure? [y/N]'),
                false
            );

            if (!$helper->ask($this->input, $this->output, $question) && $this->input->isInteractive()) {
                return Cli::RETURN_FAILURE;
            }*/
```

Works well... I have also installed the webhooks addon and use the faker now through a cronjob every n random minutes and another server gets the webhook every few minutes with customer, order or cart abandonment data :-) Perfect for demonstrations!
